In [1]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup

In [2]:
states = {
        'Alaska' : 'AK',
        'Alabama' : 'AL',
        'Arkansas' : 'AR',
        'American Samoa' : 'AS',
        'Arizona' : 'AZ',
        'California' : 'CA',
        'Colorado' : 'CO',
        'Connecticut' : 'CT',
        'District of Columbia' : 'DC' ,
        'Delaware' : 'DE',
        'Florida' : 'FL',
        'Georgia' : 'GA',
        'Guam' : 'GU' ,
        'Hawaii' : 'HI',
        'Iowa' : 'IA',
        'Idaho' : 'ID',
        'Illinois' : 'IL',
        'Indiana' : 'IN',
        'Kansas' : 'KS',
        'Kentucky' : 'KY',
        'Louisiana' : 'LA',
        'Massachusetts' : 'MA',
        'Maryland' : 'MD',
        'Maine' : 'ME',
        'Michigan' : 'MI',
        'Minnesota' : 'MN',
        'Missouri' : 'MO',
        'Northern Mariana Islands' : 'MP',
        'Mississippi' : 'MS',
        'Montana' : 'MT' ,
        'National' : 'NA',
        'North Carolina' : 'NC',
        'North Dakota' : 'ND',
        'Nebraska' : 'NE',
        'New Hampshire' : 'NH',
        'New Jersey' : 'NJ',
        'New Mexico' : 'NM',
        'Nevada' : 'NV',
        'New York' : 'NY',
        'Ohio' : 'OH',
        'Oklahoma' : 'OK',
        'Oregon' : 'OR',
        'Pennsylvania' : 'PA',
        'Puerto Rico' :  'PR',
        'Rhode Island' : 'RI',
        'South Carolina' : 'SC',
        'South Dakota' : 'SD',
        'Tennessee' : 'TN',
        'Texas' : 'TX',
        'Utah' : 'UT',
        'Virginia' : 'VA',
        'Virgin Islands' : 'VI',
        'Vermont' : 'VT',
        'Washington' : 'WA',
        'Wisconsin' : 'WI',
        'West Virginia' : 'WV',
        'Wyoming' : 'WY' 
}

In [3]:
html_doc = 'e:List of urban areas by Jewish population - Wikipedia.html'
#https://en.wikipedia.org/wiki/List_of_urban_areas_by_Jewish_population
with open(html_doc, "r", encoding='utf-8') as f:
     wiki_text= f.read()

In [4]:
soup = BeautifulSoup(wiki_text, 'html.parser')
table = soup.find_all('table')[0] 
num_of_rows=0
for row in table.find_all('tr'):    
    num_of_rows+=1

### read the table into dataframe  
in the ROW loop, we are going over all the rows in the html talbe and put it into array named data
in the COLUMN loop, we are going over the columns: City, Country, Number. 
Now, we have to clean, all the cities that are not in the US.
also, we need to clean the text:
1. clean then refernces number like [1]
2. convert the Number column to Int

In [5]:
data= [None, None, None]
num_of_jew_df = pd.DataFrame(columns=['City', 'State',  'Number', 'Latitude', 'Longtitude'], index=np.arange(0, 54)) 
row_marker = 0
for row in table.find_all('tr'):     
    column_marker = 0    
    columns = row.find_all('td')          
    for column in columns:                
        #print (column.get_text(), row.get('href'))          
        data[column_marker]=column.get_text().replace( '\n', '')
        column_marker+=1            
    if data[0] !=None:
       if 'United States' in data[1]: 
          city = data[0].replace(data[0][data[0].find('['):data[0].find(']')+1], '')          
          while  city.find('[')>0:
                 city = city.replace(city[city.find('['):city.find(']')+1], '')
          num_of_jew_df.iat[row_marker, 0]= city
          number_of_pop = data[2].replace(data[2][data[2].find('['):data[2].find(']')+1], '')          
          while number_of_pop.find(',')>0:                
                number_of_pop = number_of_pop.replace(',','')                
          num_of_jew_df.iat[row_marker, 2]= int(number_of_pop)
          row_marker +=1
    
    
num_of_jew_df

                                       City State   Number Latitude Longtitude
0                             New York City   NaN  1100000      NaN        NaN
1                               Los Angeles   NaN   519200      NaN        NaN
2                    San Francisco Bay Area   NaN   391550      NaN        NaN
3                                   Chicago   NaN   291800      NaN        NaN
4                                    Boston   NaN   248000      NaN        NaN
5                          Washington, D.C.   NaN   215600      NaN        NaN
6                              Philadelphia   NaN   214600      NaN        NaN
7                                   Atlanta   NaN   119800      NaN        NaN
8                                     Miami   NaN   119000      NaN        NaN
9                                 San Diego   NaN   100000      NaN        NaN
10                   Cleveland-Akron-Canton   NaN    86600      NaN        NaN
11                           Denver-Boulder   NaN    83900      NaN        NaN
12                                  Phoenix   NaN    82900      NaN        NaN
13                         Las Vegas Valley   NaN    80000      NaN        NaN
14                            Metro Detroit   NaN    78000      NaN        NaN
15                                  Seattle   NaN    63400      NaN        NaN
16                        Dallas-Fort Worth   NaN    57800      NaN        NaN
17                                St. Louis   NaN    54500      NaN        NaN
18  Tampa Bay Area (Tampa-Saint Petersburg)   NaN    51100      NaN        NaN
19                                  Houston   NaN    48400      NaN        NaN
20                                 Portland   NaN    47500      NaN        NaN
21                               Pittsburgh   NaN    42200      NaN        NaN
22                   Minneapolis-Saint Paul   NaN    40240      NaN        NaN
23                                 Hartford   NaN    34500      NaN        NaN
24                                New Haven   NaN    29700      NaN        NaN
25                               Cincinnati   NaN    27000      NaN        NaN
26                                Milwaukee   NaN    25800      NaN        NaN
27                                   Tucson   NaN    22900      NaN        NaN
28                                Rochester   NaN    22500      NaN        NaN
29                                 Columbus   NaN    25500      NaN        NaN
30                              Kansas City   NaN    19000      NaN        NaN
31                                  Orlando   NaN    19000      NaN        NaN
32                                   Austin   NaN    16300      NaN        NaN
33                             Jacksonville   NaN    15000      NaN        NaN
34                               Providence   NaN    14200      NaN        NaN
35                                  Buffalo   NaN    13000      NaN        NaN
36                              San Antonio   NaN    12740      NaN        NaN
37                                 Richmond   NaN    12500      NaN        NaN
38                                   Albany   NaN    12500      NaN        NaN
39                                Charlotte   NaN    12000      NaN        NaN
40                              New Orleans   NaN    12000      NaN        NaN
41                             Indianapolis   NaN    10000      NaN        NaN
42                               Louisville   NaN     8700      NaN        NaN
43                                Nashville   NaN     8000      NaN        NaN
44                              Chapel Hill   NaN     6000      NaN        NaN
45                                  Raleigh   NaN     6000      NaN        NaN
46                               Birmingham   NaN     5300      NaN        NaN
47                                  El Paso   NaN     5000      NaN        NaN
48                                  Madison   NaN     5000      NaN        NaN
49                                   Dayton   NaN     4000      NaN        NaN
50                                   Toledo   NaN     3900      NaN        NaN
51                               Youngstown   NaN     3200      NaN        NaN
52                               Greensboro   NaN     3000      NaN        NaN
53                               Montgomery   NaN     1200      NaN        NaN

Now, we are looking only for cities that have less than 50,000

In [6]:
num_of_jew_df = num_of_jew_df.drop(num_of_jew_df[num_of_jew_df.Number > 50000].index)
num_of_jew_df

                      City State Number Latitude Longtitude
19                 Houston   NaN  48400      NaN        NaN
20                Portland   NaN  47500      NaN        NaN
21              Pittsburgh   NaN  42200      NaN        NaN
22  Minneapolis-Saint Paul   NaN  40240      NaN        NaN
23                Hartford   NaN  34500      NaN        NaN
24               New Haven   NaN  29700      NaN        NaN
25              Cincinnati   NaN  27000      NaN        NaN
26               Milwaukee   NaN  25800      NaN        NaN
27                  Tucson   NaN  22900      NaN        NaN
28               Rochester   NaN  22500      NaN        NaN
29                Columbus   NaN  25500      NaN        NaN
30             Kansas City   NaN  19000      NaN        NaN
31                 Orlando   NaN  19000      NaN        NaN
32                  Austin   NaN  16300      NaN        NaN
33            Jacksonville   NaN  15000      NaN        NaN
34              Providence   NaN  14200      NaN        NaN
35                 Buffalo   NaN  13000      NaN        NaN
36             San Antonio   NaN  12740      NaN        NaN
37                Richmond   NaN  12500      NaN        NaN
38                  Albany   NaN  12500      NaN        NaN
39               Charlotte   NaN  12000      NaN        NaN
40             New Orleans   NaN  12000      NaN        NaN
41            Indianapolis   NaN  10000      NaN        NaN
42              Louisville   NaN   8700      NaN        NaN
43               Nashville   NaN   8000      NaN        NaN
44             Chapel Hill   NaN   6000      NaN        NaN
45                 Raleigh   NaN   6000      NaN        NaN
46              Birmingham   NaN   5300      NaN        NaN
47                 El Paso   NaN   5000      NaN        NaN
48                 Madison   NaN   5000      NaN        NaN
49                  Dayton   NaN   4000      NaN        NaN
50                  Toledo   NaN   3900      NaN        NaN
51              Youngstown   NaN   3200      NaN        NaN
52              Greensboro   NaN   3000      NaN        NaN
53              Montgomery   NaN   1200      NaN        NaN

Find state

In [7]:
html_doc = 'e:List of largest cities of U.S. states and territories by population - Wikipedia.html'
#https://en.wikipedia.org/wiki/List_of_largest_cities_of_U.S._states_and_territories_by_population
with open(html_doc, "r", encoding='utf-8') as f:
     wiki_text= f.read()
soup = BeautifulSoup(wiki_text, 'html.parser')

table = soup.find_all('table')[0]   
row_marker = 0

data= [None, None]
states_df = pd.DataFrame(columns=['City', 'State', 'Short_state'], index=np.arange(0, 35)) 

for index, line_of_city in  num_of_jew_df.iterrows():    
    for row in table.find_all('tr'):     
        find_state = False
        column_marker = 0    
        columns = row.find_all('td')                   
        for column in columns:                                
            if column_marker == 0:
               state = column.get_text().replace( '\n', '').replace('\xa0', '')     
            else:               
               states_df.iat[index-19, 0] = line_of_city['City']
               if  line_of_city['City'] in  column.get_text().replace( '\n', ''):                                                        
                   states_df.iat[index-19, 1]= state
                   states_df.iat[index-19, 2]= states[state]                                                                      
                   find_state = True
                   break                                                
            column_marker+=1
        if find_state == True:
           break        

states_df

                      City           State Short_state
0                  Houston           Texas          TX
1                 Portland           Maine          ME
2               Pittsburgh    Pennsylvania          PA
3   Minneapolis-Saint Paul             NaN         NaN
4                 Hartford     Connecticut          CT
5                New Haven     Connecticut          CT
6               Cincinnati            Ohio          OH
7                Milwaukee       Wisconsin          WI
8                   Tucson         Arizona          AZ
9                Rochester       Minnesota          MN
10                Columbus         Georgia          GA
11             Kansas City          Kansas          KS
12                 Orlando         Florida          FL
13                  Austin           Texas          TX
14            Jacksonville         Florida          FL
15              Providence    Rhode Island          RI
16                 Buffalo        New York          NY
17             San Antonio           Texas          TX
18                Richmond        Virginia          VA
19                  Albany        New York          NY
20               Charlotte  North Carolina          NC
21             New Orleans       Louisiana          LA
22            Indianapolis         Indiana          IN
23              Louisville        Kentucky          KY
24               Nashville       Tennessee          TN
25             Chapel Hill             NaN         NaN
26                 Raleigh  North Carolina          NC
27              Birmingham         Alabama          AL
28                 El Paso             NaN         NaN
29                 Madison       Wisconsin          WI
30                  Dayton             NaN         NaN
31                  Toledo            Ohio          OH
32              Youngstown             NaN         NaN
33              Greensboro  North Carolina          NC
34              Montgomery         Alabama          AL

In [8]:
#num_of_jew_df.set_index('City', inplace=True) 
#states_df.set_index('City', inplace=True) 
#states_df

In [9]:
num_of_jew_df = num_of_jew_df.merge(states_df, left_on='City', right_on='City')
                                  #left_index=True, right_index=True)

In [10]:
num_of_jew_df.iat[1, 5] = 'Oregon'
num_of_jew_df.iat[1, 6]= states['Oregon']
num_of_jew_df.iat[3, 0]= 'Minneapolis'
num_of_jew_df.iat[3, 5]= 'Minnesota'
num_of_jew_df.iat[3, 6]= states['Minnesota']
num_of_jew_df.iat[9, 5] = 'New York'
num_of_jew_df.iat[9, 6]= states['New York']
num_of_jew_df.iat[10, 5] = 'Ohio'
num_of_jew_df.iat[10, 6]= states['Ohio']
num_of_jew_df.iat[25, 5] = 'North Carolina'
num_of_jew_df.iat[25, 6]= states['North Carolina']
num_of_jew_df.iat[28, 5] = 'Texas'
num_of_jew_df.iat[28, 6]= states['Texas']
num_of_jew_df.iat[30, 5] = 'Ohio'
num_of_jew_df.iat[30, 6]= states['Ohio']
num_of_jew_df.iat[32, 5] = 'Ohio'
num_of_jew_df.iat[32, 6]= states['Ohio']

num_of_jew_df

,City,State_x,Number,Latitude,Longtitude,State_y,Short_state
0,Houston,NaN,48400,NaN,NaN,Texas,TX
1,Portland,NaN,47500,NaN,NaN,Oregon,OR
2,Pittsburgh,NaN,42200,NaN,NaN,Pennsylvania,PA
3,Minneapolis,NaN,40240,NaN,NaN,Minnesota,MN
4,Hartford,NaN,34500,NaN,NaN,Connecticut,CT
5,New Haven,NaN,29700,NaN,NaN,Connecticut,CT
6,Cincinnati,NaN,27000,NaN,NaN,Ohio,OH
7,Milwaukee,NaN,25800,NaN,NaN,Wisconsin,WI
8,Tucson,NaN,22900,NaN,NaN,Arizona,AZ
9,Rochester,NaN,22500,NaN,NaN,New York,NY
10,Columbus,NaN,25500,NaN,NaN,Ohio,OH
11,Kansas City,NaN,19000,NaN,NaN,Kansas,KS
12,Orlando,NaN,19000,NaN,NaN,Florida,FL
13,Austin,NaN,16300,NaN,NaN,Texas,TX
14,Jacksonville,NaN,15000,NaN,NaN,Florida,FL
15,Providence,NaN,14200,NaN,NaN,Rhode Island,RI
16,Buffalo,NaN,13000,NaN,NaN,New York,NY
17,San Antonio,NaN,12740,NaN,NaN,Texas,TX
18,Richmond,NaN,12500,NaN,NaN,Virginia,VA
19,Albany,NaN,12500,NaN,NaN,New York,NY
20,Charlotte,NaN,12000,NaN,NaN,North Carolina,NC
21,New Orleans,NaN,12000,NaN,NaN,Louisiana,LA
22,Indianapolis,NaN,10000,NaN,NaN,Indiana,IN
23,Louisville,NaN,8700,NaN,NaN,Kentucky,KY
24,Nashville,NaN,8000,NaN,NaN,Tennessee,TN
25,Chapel Hill,NaN,6000,NaN,NaN,North Carolina,NC
26,Raleigh,NaN,6000,NaN,NaN,North Carolina,NC
27,Birmingham,NaN,5300,NaN,NaN,Alabama,AL
28,El Paso,NaN,5000,NaN,NaN,Texas,TX
29,Madison,NaN,5000,NaN,NaN,Wisconsin,WI
30,Dayton,NaN,4000,NaN,NaN,Ohio,OH
31,Toledo,NaN,3900,NaN,NaN,Ohio,OH
32,Youngstown,NaN,3200,NaN,NaN,Ohio,OH
33,Greensboro,NaN,3000,NaN,NaN,North Carolina,NC
34,Montgomery,NaN,1200,NaN,NaN,Alabama,AL

In [11]:
num_of_jew_df.drop(['State_x'], inplace=True, axis=1)
num_of_jew_df.rename(columns={"State_y": "State"}, inplace=True)
num_of_jew_df

            City Number Latitude Longtitude           State Short_state
0        Houston  48400      NaN        NaN           Texas          TX
1       Portland  47500      NaN        NaN          Oregon          OR
2     Pittsburgh  42200      NaN        NaN    Pennsylvania          PA
3    Minneapolis  40240      NaN        NaN       Minnesota          MN
4       Hartford  34500      NaN        NaN     Connecticut          CT
5      New Haven  29700      NaN        NaN     Connecticut          CT
6     Cincinnati  27000      NaN        NaN            Ohio          OH
7      Milwaukee  25800      NaN        NaN       Wisconsin          WI
8         Tucson  22900      NaN        NaN         Arizona          AZ
9      Rochester  22500      NaN        NaN        New York          NY
10      Columbus  25500      NaN        NaN            Ohio          OH
11   Kansas City  19000      NaN        NaN          Kansas          KS
12       Orlando  19000      NaN        NaN         Florida          FL
13        Austin  16300      NaN        NaN           Texas          TX
14  Jacksonville  15000      NaN        NaN         Florida          FL
15    Providence  14200      NaN        NaN    Rhode Island          RI
16       Buffalo  13000      NaN        NaN        New York          NY
17   San Antonio  12740      NaN        NaN           Texas          TX
18      Richmond  12500      NaN        NaN        Virginia          VA
19        Albany  12500      NaN        NaN        New York          NY
20     Charlotte  12000      NaN        NaN  North Carolina          NC
21   New Orleans  12000      NaN        NaN       Louisiana          LA
22  Indianapolis  10000      NaN        NaN         Indiana          IN
23    Louisville   8700      NaN        NaN        Kentucky          KY
24     Nashville   8000      NaN        NaN       Tennessee          TN
25   Chapel Hill   6000      NaN        NaN  North Carolina          NC
26       Raleigh   6000      NaN        NaN  North Carolina          NC
27    Birmingham   5300      NaN        NaN         Alabama          AL
28       El Paso   5000      NaN        NaN           Texas          TX
29       Madison   5000      NaN        NaN       Wisconsin          WI
30        Dayton   4000      NaN        NaN            Ohio          OH
31        Toledo   3900      NaN        NaN            Ohio          OH
32    Youngstown   3200      NaN        NaN            Ohio          OH
33    Greensboro   3000      NaN        NaN  North Carolina          NC
34    Montgomery   1200      NaN        NaN         Alabama          AL

In [23]:
from geopy.geocoders import Nominatim
import folium
import requests # library to handle requests

# Matplotlib and associated plotting modules
import matplotlib.cm as cm
import matplotlib.colors as colors

# import k-means from clustering stage
from sklearn.cluster import KMeans

In [24]:
geolocator = Nominatim(user_agent="ny_explorer")
for index, line_of_city in  num_of_jew_df.iterrows():
    address = line_of_city['City']+', '+line_of_city['Short_state']
    location = geolocator.geocode(address)
    if location != None:
       latitude  = location.latitude
       longitude = location.longitude
       num_of_jew_df.iat[index, 2] = latitude
       num_of_jew_df.iat[index, 3] = longitude
    
num_of_jew_df

            City Number Latitude Longtitude           State Short_state
0        Houston  48400  29.7589   -95.3677           Texas          TX
1       Portland  47500  45.5202   -122.674          Oregon          OR
2     Pittsburgh  42200  40.4417   -79.9901    Pennsylvania          PA
3    Minneapolis  40240  44.9773   -93.2655       Minnesota          MN
4       Hartford  34500  41.7646   -72.6909     Connecticut          CT
5      New Haven  29700  41.3082   -72.9251     Connecticut          CT
6     Cincinnati  27000  39.1015   -84.5125            Ohio          OH
7      Milwaukee  25800   43.035   -87.9225       Wisconsin          WI
8         Tucson  22900  32.2219   -110.926         Arizona          AZ
9      Rochester  22500  43.1573   -77.6152        New York          NY
10      Columbus  25500  39.9623   -83.0007            Ohio          OH
11   Kansas City  19000  39.1135   -94.6265          Kansas          KS
12       Orlando  19000  28.5421    -81.379         Florida          FL
13        Austin  16300  30.2711   -97.7437           Texas          TX
14  Jacksonville  15000  30.3322   -81.6557         Florida          FL
15    Providence  14200  41.8677   -71.5815    Rhode Island          RI
16       Buffalo  13000  42.8867   -78.8784        New York          NY
17   San Antonio  12740  29.4246   -98.4951           Texas          TX
18      Richmond  12500  37.5385   -77.4343        Virginia          VA
19        Albany  12500  42.6512    -73.755        New York          NY
20     Charlotte  12000  35.2271   -80.8431  North Carolina          NC
21   New Orleans  12000  29.9499   -90.0701       Louisiana          LA
22  Indianapolis  10000  39.7683   -86.1584         Indiana          IN
23    Louisville   8700  38.2542   -85.7594        Kentucky          KY
24     Nashville   8000  36.1622   -86.7744       Tennessee          TN
25   Chapel Hill   6000  35.9132   -79.0558  North Carolina          NC
26       Raleigh   6000  35.7804   -78.6391  North Carolina          NC
27    Birmingham   5300  33.5207   -86.8024         Alabama          AL
28       El Paso   5000    31.76   -106.487           Texas          TX
29       Madison   5000  43.0748   -89.3838       Wisconsin          WI
30        Dayton   4000  39.7589   -84.1916            Ohio          OH
31        Toledo   3900  41.6787   -83.5127            Ohio          OH
32    Youngstown   3200  41.1036    -80.652            Ohio          OH
33    Greensboro   3000  36.0726    -79.792  North Carolina          NC
34    Montgomery   1200   32.367   -86.3006         Alabama          AL

Another data I eant to find, is the changes in the population number, in the last years
If in a state, the population has grown, it means that the community there is develop, and the opposite

In [25]:
changes_pop_df = pd.read_csv('e:Change in Jewish Population, 1960-2015.csv', usecols=['State', '1990', '2017'])
#geo_x_y = pd.read_csv("http://cocl.us/Geospatial_data")
changes_pop_df['change'] = changes_pop_df['2017'] - changes_pop_df['1990']
changes_pop_df

                   State     1990     2017  change
0                Alabama     9300     9525     225
1                 Alaska     2400     5750    3350
2                Arizona    71500   106725   35225
3               Arkansas     2000     2225     225
4             California   919500  1230540  311040
5               Colorado    50000   102600   52600
6            Connecticut   113200   117850    4650
7               Delaware     9500    15100    5600
8   District of Columbia    25400    28000    2600
9                Florida   567000   621460   54460
10               Georgia    72500   128520   56020
11               Hawai'i     7000     7100     100
12                 Idaho      450     2125    1675
13              Illinois   257400   298035   40635
14               Indiana    18300    17345    -955
15                  Iowa     6350     5450    -900
16                Kansas    14000    17300    3300
17              Kentucky    11800    11200    -600
18             Louisiana    15700    13900   -1800
19                 Maine     8400    12550    4150
20              Maryland   211000   240000   29000
21         Massachusetts   276000   293080   17080
22              Michigan   107300    83155  -24145
23             Minnesota    30500    45600   15100
24           Mississippi     1900     1525    -375
25              Missouri    61600    64275    2675
26               Montana      450     1395     945
27              Nebraska     7400     9350    1950
28                Nevada    20500    76300   55800
29         New Hampshire     7000    10120    3120
30            New Jersey   430000   545450  115450
31            New Mexico     6400    12625    6225
32              New York  1843000  1759570  -83430
33        North Carolina    16300    35435   19135
34          North Dakota      750      400    -350
35                  Ohio   130800   147715   16915
36              Oklahoma     5300     4625    -675
37                Oregon    12500    40650   28150
38          Pennsylvania   330500   291140  -39360
39          Rhode Island    16100    18750    2650
40        South Carolina     9300    13820    4520
41          South Dakota      350      250    -100
42             Tennessee    19400    19800     400
43                 Texas   109000   166505   57505
44                  Utah     3100     5650    2550
45               Vermont     4800     5985    1185
46              Virginia    67600    95695   28095
47            Washington    32800    72185   39385
48         West Virginia     2400     2310     -90
49             Wisconsin    34700    33055   -1645
50               Wyoming      450     1150     700
51                 Total  5980900  6850865  869965

In [26]:
num_of_jew_df = num_of_jew_df.merge(changes_pop_df, left_on='State', right_on='State')
num_of_jew_df

,City,Number,Latitude,Longtitude,State,Short_state,1990,2017,change
0,Houston,48400,29.7589,-95.3677,Texas,TX,109000,166505,57505
1,Austin,16300,30.2711,-97.7437,Texas,TX,109000,166505,57505
2,San Antonio,12740,29.4246,-98.4951,Texas,TX,109000,166505,57505
3,El Paso,5000,31.76,-106.487,Texas,TX,109000,166505,57505
4,Portland,47500,45.5202,-122.674,Oregon,OR,12500,40650,28150
5,Pittsburgh,42200,40.4417,-79.9901,Pennsylvania,PA,330500,291140,-39360
6,Minneapolis,40240,44.9773,-93.2655,Minnesota,MN,30500,45600,15100
7,Hartford,34500,41.7646,-72.6909,Connecticut,CT,113200,117850,4650
8,New Haven,29700,41.3082,-72.9251,Connecticut,CT,113200,117850,4650
9,Cincinnati,27000,39.1015,-84.5125,Ohio,OH,130800,147715,16915
10,Columbus,25500,39.9623,-83.0007,Ohio,OH,130800,147715,16915
11,Dayton,4000,39.7589,-84.1916,Ohio,OH,130800,147715,16915
12,Toledo,3900,41.6787,-83.5127,Ohio,OH,130800,147715,16915
13,Youngstown,3200,41.1036,-80.652,Ohio,OH,130800,147715,16915
14,Milwaukee,25800,43.035,-87.9225,Wisconsin,WI,34700,33055,-1645
15,Madison,5000,43.0748,-89.3838,Wisconsin,WI,34700,33055,-1645
16,Tucson,22900,32.2219,-110.926,Arizona,AZ,71500,106725,35225
17,Rochester,22500,43.1573,-77.6152,New York,NY,1843000,1759570,-83430
18,Buffalo,13000,42.8867,-78.8784,New York,NY,1843000,1759570,-83430
19,Albany,12500,42.6512,-73.755,New York,NY,1843000,1759570,-83430
20,Kansas City,19000,39.1135,-94.6265,Kansas,KS,14000,17300,3300
21,Orlando,19000,28.5421,-81.379,Florida,FL,567000,621460,54460
22,Jacksonville,15000,30.3322,-81.6557,Florida,FL,567000,621460,54460
23,Providence,14200,41.8677,-71.5815,Rhode Island,RI,16100,18750,2650
24,Richmond,12500,37.5385,-77.4343,Virginia,VA,67600,95695,28095
25,Charlotte,12000,35.2271,-80.8431,North Carolina,NC,16300,35435,19135
26,Chapel Hill,6000,35.9132,-79.0558,North Carolina,NC,16300,35435,19135
27,Raleigh,6000,35.7804,-78.6391,North Carolina,NC,16300,35435,19135
28,Greensboro,3000,36.0726,-79.792,North Carolina,NC,16300,35435,19135
29,New Orleans,12000,29.9499,-90.0701,Louisiana,LA,15700,13900,-1800
30,Indianapolis,10000,39.7683,-86.1584,Indiana,IN,18300,17345,-955
31,Louisville,8700,38.2542,-85.7594,Kentucky,KY,11800,11200,-600
32,Nashville,8000,36.1622,-86.7744,Tennessee,TN,19400,19800,400
33,Birmingham,5300,33.5207,-86.8024,Alabama,AL,9300,9525,225
34,Montgomery,1200,32.367,-86.3006,Alabama,AL,9300,9525,225

Now, let's see, in what country, the Jewish communities have grown the most.

In [27]:
state_change_df = pd.DataFrame(columns=['State', 'changes'], index=np.arange(0, 35))
state_change_df['State'] = num_of_jew_df['State'].values
state_change_df['change'] = num_of_jew_df['change'].values
#state_change_df.drop('City', axis =1, inplace=True)
#state_change_df.drop('Number',     axis =1, inplace=True)
#state_change_df.drop('Latitude',   axis =1, inplace=True)
#state_change_df.drop('Longtitude', axis =1, inplace=True)
state_change_df.drop_duplicates(inplace=True)
#state_change_df
#num_of_jew_df

In [28]:
import matplotlib.pyplot as plt

x_pos = state_change_df['State']
y_pos = state_change_df['change']#state_change_df['change']

fig, ax = plt.subplots(figsize=(20, 8))
bar_width = 0.28
index = np.arange(state_change_df['State'].count())


bar1 = ax.bar(index,  y_pos,  bar_width,  color='blue')
ax.set_xticks(index + (bar_width))
ax.set_xticklabels(x_pos.values, fontsize=14, rotation='vertical')
ax.set_title('Changes in the last years, in Jewish population', fontsize=16)

plt.show()

In [29]:
from geopy.geocoders import Nominatim
import folium
import requests # library to handle requests

# Matplotlib and associated plotting modules
import matplotlib.cm as cm
import matplotlib.colors as colors

# import k-means from clustering stage
from sklearn.cluster import KMeans

In [30]:
address = 'USA'

geolocator = Nominatim(user_agent="ny_explorer")
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print('The geograpical coordinate of USA are {}, {}.'.format(latitude, longitude))

The geograpical coordinate of USA are 39.7837304, -100.4458825.

In [31]:
# create map of USA using latitude and longitude values
map_usa = folium.Map(location=[latitude, longitude], zoom_start=4, tiles='OpenStreetMap')
map_usa

In [32]:
for lat, lng, label in zip(num_of_jew_df['Latitude'], num_of_jew_df['Longtitude'], num_of_jew_df['City']):
    label = folium.Popup(label, parse_html=True)
    if lat != None:
       folium.CircleMarker(
           [lat, lng],
           radius=5,
           popup=label,
           color='blue',
           fill=True,
           fill_color='#3186cc',
           fill_opacity=0.7).add_to(map_usa)
map_usa

In [33]:
CLIENT_ID = 'KL0223UZZBLIMJVAOBWRVBUSQLCD1LJ5TL2KLD0IVVFU5CMJ' # your Foursquare ID
CLIENT_SECRET = 'VWI3LJER2CUK5DMKVMMVZSRR3ESZUCXFVPSRQSSLVIXLYH54' # your Foursquare Secret
VERSION = '20190308' # Foursquare API version

print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: KL0223UZZBLIMJVAOBWRVBUSQLCD1LJ5TL2KLD0IVVFU5CMJ
CLIENT_SECRET:VWI3LJER2CUK5DMKVMMVZSRR3ESZUCXFVPSRQSSLVIXLYH54

In [52]:
def getNearbyVenues(names, latitudes, longitudes, radius=3000):
    category_list='52e81612bcbc57f1066b79fd,52e81612bcbc57f1066b79fc,52e81612bcbc57f1066b7a41,4bf58dd8d48988d139941735,52e81612bcbc57f1066b7a47'
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}&categoryId={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT,
            category_list
            )
            
        # make the GET request
        results = requests.get(url).json()["response"]['groups'][0]['items']
        
        # return only relevant information for each nearby venue
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['City', 
                  'City Latitude', 
                  'City Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

In [53]:
LIMIT = 100
community_venues = getNearbyVenues(names=num_of_jew_df['City'],
                                 latitudes=num_of_jew_df['Latitude'],
                                 longitudes=num_of_jew_df['Longtitude']
                                )

Houston
Austin
San Antonio
El Paso
Portland
Pittsburgh
Minneapolis
Hartford
New Haven
Cincinnati
Columbus
Dayton
Toledo
Youngstown
Milwaukee
Madison
Tucson
Rochester
Buffalo
Albany
Kansas City
Orlando
Jacksonville
Providence
Richmond
Charlotte
Chapel Hill
Raleigh
Greensboro
New Orleans
Indianapolis
Louisville
Nashville
Birmingham
Montgomery

In [54]:
print(community_venues.shape)
community_venues

(65, 7)

,City,City Latitude,City Longitude,Venue,Venue Latitude,Venue Longitude,Venue Category
0,Houston,29.758938,-95.367697,Katz's Deli & Bar,29.744723,-95.389680,Deli / Bodega
1,Houston,29.758938,-95.367697,Whole Foods Market,29.757994,-95.397643,Grocery Store
2,Austin,30.271129,-97.743700,Chabad @ the University of Texas,30.284007,-97.743849,Synagogue
3,Austin,30.271129,-97.743700,This Knish,30.274010,-97.719154,Jewish Restaurant
4,Austin,30.271129,-97.743700,Allan House,30.274342,-97.745938,Event Space
5,San Antonio,29.424600,-98.495141,Temple Beth-El,29.448854,-98.498238,Synagogue
6,El Paso,31.760037,-106.487287,chispaspiratus,31.754213,-106.492886,Religious School
7,El Paso,31.760037,-106.487287,Executive Bathroom,31.781542,-106.469815,Prayer Room
8,Portland,45.520247,-122.674195,Kenny & Zuke's Delicatessen,45.522205,-122.681983,Sandwich Place
9,Portland,45.520247,-122.674195,Kornblatt's Deli,45.527396,-122.698478,Deli / Bodega
10,Portland,45.520247,-122.674195,Temple Beth Israel,45.525630,-122.691364,Synagogue
11,Portland,45.520247,-122.674195,Havurah Shalom,45.529123,-122.689656,Synagogue
12,Portland,45.520247,-122.674195,Congregation Shaarie Torah,45.529463,-122.701880,Synagogue
13,Portland,45.520247,-122.674195,Oregon Jewish Museum & Center for Holocaust Ed...,45.524314,-122.678327,History Museum
14,Pittsburgh,40.441694,-79.990086,Jewish Federation of Greater Pittsburgh,40.438977,-79.958496,Religious School
15,Minneapolis,44.977300,-93.265469,The Eisenberg Residence At The Carlyle,44.981366,-93.262180,Synagogue
16,Minneapolis,44.977300,-93.265469,TAO Natural Foods,44.960946,-93.293183,Acupuncturist
17,Minneapolis,44.977300,-93.265469,Heather Bowman's Wondrous Japanese Car Factory,44.968740,-93.281791,Synagogue
18,Minneapolis,44.977300,-93.265469,Friends of Lisa Frank - Tena Support Group - C...,44.994736,-93.248326,Synagogue
19,Minneapolis,44.977300,-93.265469,Hodroff-Epstein Memorial Chapel,44.962939,-93.275239,Event Space
20,Hartford,41.764582,-72.690855,Beth Israel,41.764511,-72.718909,Synagogue
21,Hartford,41.764582,-72.690855,Conn & Conn Co.,41.765424,-72.715253,Coworking Space
22,Hartford,41.764582,-72.690855,Congregation Beth Israel (West Hartford),41.764718,-72.719327,Synagogue
23,New Haven,41.308214,-72.925052,Brick Oven Pizza,41.312147,-72.933799,Pizza Place
24,New Haven,41.308214,-72.925052,Est Est Est Pizza & Restaurant,41.308947,-72.933491,Pizza Place
25,New Haven,41.308214,-72.925052,Edge Of The Woods,41.318001,-72.945259,Grocery Store
26,New Haven,41.308214,-72.925052,Slifka Center for Jewish Life at Yale,41.310231,-72.925237,Student Center
27,Cincinnati,39.101454,-84.512460,Plum Street Temple,39.103783,-84.518482,Synagogue
28,Columbus,39.962260,-83.000707,Katzinger's Delicatessen,39.952697,-82.996178,Deli / Bodega
29,Dayton,39.758948,-84.191607,Temple Israel,39.769113,-84.190035,Synagogue
...,...,...,...,...,...,...,...
35,Madison,43.074761,-89.383761,Adamah - Neighborhood Table,43.075753,-89.396089,Jewish Restaurant
36,Madison,43.074761,-89.383761,Hillel,43.075703,-89.395979,Student Center
37,Tucson,32.221892,-110.926235,Temple Emanu-El,32.224088,-110.927161,Synagogue
38,Buffalo,42.886717,-78.878392,Risa's,42.892259,-78.875807,Jewish Restaurant
39,Buffalo,42.886717,-78.878392,Temple Beth Zion,42.906189,-78.870511,Synagogue
40,Albany,42.651167,-73.754968,Beth Emeth,42.646497,-73.784701,Synagogue
41,Albany,42.651167,-73.754968,St Matthew School & Day Care,42.641190,-73.787620,Preschool
42,Orlando,28.542110,-81.379039,The Christ School,28.539710,-81.376650,Private School
43,Richmond,37.538509,-77.434280,Perly's,37.543848,-77.441436,Deli / Bodega
44,Richmond,37.538509,-77.434280,Virginia Holocaust Museum,37.530940,-77.426121,History Museum
45,Richmond,37.538509,-77.434280,Congregation Beth Ahabah,37.551006,-77.455500,Synagogue
46,Charlotte,35.227087,-80.843127,Brookstone Schools,35.220019,-80.840702,Religious School
47,Charlotte,35.227087,-80.843127,Jewsteins,35.213407,-80.867677,Synagogue
48,Chapel Hill,35.913154,-79.055780,MSA prayer room,35.909840,-79.047644,Prayer Room
49,Chapel Hill,35.913154,-79.055780,430 Mason St,35.918189,-79.065319,Synagogue
50,Chapel Hill,35.913154,-79.055780,Chapel Hill Kehillah,35.898547,-79.050338,Synagogue
51,Chapel Hill,35.913154,-79.055780,Kehillah Synagogue,35.898356,-79.050108,Synagogue
52,Chapel Hill,35.913154,-79.055780,Jack's House,35.912104,-79.081316,Prayer Room
53,New Orleans,29.949932,-90.070116,Stein's Market & Deli,29.929522,-90.077001,Deli / Bodega
54,New Orleans,29.949932,-90.070116,Horn's,29.965358,-90.059125,American Restaurant
55,New Orleans,29.949932,-90.070116,Surrey's Cafe & Juice Bar,29.935777,-90.071885,Breakfast Spot
56,New Orleans,29.949932,-90.070116,Anshei Sfard,29.934472,-90.082000,Synagogue
57,New Orleans,29.949932,-90.070116,New Orleans Christian Academy,29.965060,-90.085193,Religious School
58,Indianapolis,39.768333,-86.158350,Shapiro's Delicatessen,39.756209,-86.159384,Deli / Bodega
59,Indianapolis,39.768333,-86.158350,Dorman Street Saloon,39.779055,-86.138883,Bar
60,Indianapolis,39.768333,-86.158350,Emmaus Lutheran School,39.750140,-86.135720,Religious School
61,Louisville,38.254238,-85.759407,Open Door Of Mercy,38.252137,-85.758691,Prayer Room
62,Louisville,38.254238,-85.759407,Wall Street Deli,38.249271,-85.751016,Sandwich Place
63,Birmingham,33.520682,-86.802433,Temple Emanu-El,33.500254,-86.793546,Synagogue
64,Birmingham,33.520682,-86.802433,Temple Beth El,33.500090,-86.790161,Synagogue

In [55]:
community_venues.groupby('City').count()

,City Latitude,City Longitude,Venue,Venue Latitude,Venue Longitude,Venue Category
City,,,,,,
Albany,2,2,2,2,2,2
Austin,3,3,3,3,3,3
Birmingham,2,2,2,2,2,2
Buffalo,2,2,2,2,2,2
Chapel Hill,5,5,5,5,5,5
Charlotte,2,2,2,2,2,2
Cincinnati,1,1,1,1,1,1
Columbus,1,1,1,1,1,1
Dayton,2,2,2,2,2,2
El Paso,2,2,2,2,2,2
Hartford,3,3,3,3,3,3
Houston,2,2,2,2,2,2
Indianapolis,3,3,3,3,3,3
Louisville,2,2,2,2,2,2
Madison,4,4,4,4,4,4
Milwaukee,1,1,1,1,1,1
Minneapolis,5,5,5,5,5,5
New Haven,4,4,4,4,4,4
New Orleans,5,5,5,5,5,5
Orlando,1,1,1,1,1,1
Pittsburgh,1,1,1,1,1,1
Portland,6,6,6,6,6,6
Richmond,3,3,3,3,3,3
San Antonio,1,1,1,1,1,1
Tucson,1,1,1,1,1,1
Youngstown,1,1,1,1,1,1

### Let's find out how many unique categories can be curated from all the returned venues

In [56]:
print('There are {} uniques categories.'.format(len(community_venues['Venue Category'].unique())))

There are 18 uniques categories.

## Analyze Each Neighborhood

In [57]:
# one hot encoding
community_onehot = pd.get_dummies(community_venues[['Venue Category']], prefix="", prefix_sep="")

# add neighborhood column back to dataframe
community_onehot['City'] = community_venues['City'] 

# move neighborhood column to the first column
fixed_columns = [community_onehot.columns[-1]] + list(community_onehot.columns[:-1])
community_onehot = community_onehot[fixed_columns]

community_onehot

,City,Acupuncturist,American Restaurant,Bar,Breakfast Spot,Coworking Space,Deli / Bodega,Event Space,Grocery Store,History Museum,Jewish Restaurant,Pizza Place,Prayer Room,Preschool,Private School,Religious School,Sandwich Place,Student Center,Synagogue
0,Houston,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
1,Houston,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
2,Austin,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
3,Austin,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
4,Austin,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
5,San Antonio,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
6,El Paso,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
7,El Paso,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
8,Portland,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
9,Portland,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
10,Portland,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
11,Portland,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
12,Portland,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
13,Portland,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
14,Pittsburgh,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
15,Minneapolis,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
16,Minneapolis,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
17,Minneapolis,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
18,Minneapolis,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
19,Minneapolis,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
20,Hartford,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
21,Hartford,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
22,Hartford,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
23,New Haven,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
24,New Haven,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
25,New Haven,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
26,New Haven,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
27,Cincinnati,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
28,Columbus,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
29,Dayton,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35,Madison,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
36,Madison,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
37,Tucson,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
38,Buffalo,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
39,Buffalo,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
40,Albany,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
41,Albany,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
42,Orlando,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
43,Richmond,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
44,Richmond,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
45,Richmond,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
46,Charlotte,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
47,Charlotte,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
48,Chapel Hill,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
49,Chapel Hill,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
50,Chapel Hill,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
51,Chapel Hill,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
52,Chapel Hill,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
53,New Orleans,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
54,New Orleans,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
55,New Orleans,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
56,New Orleans,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
57,New Orleans,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
58,Indianapolis,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
59,Indianapolis,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
60,Indianapolis,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
61,Louisville,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
62,Louisville,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
63,Birmingham,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
64,Birmingham,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1

In [58]:
community_onehot.shape

(65, 19)

In [59]:
community_grouped = community_onehot.groupby('City').mean().reset_index()
community_grouped

,City,Acupuncturist,American Restaurant,Bar,Breakfast Spot,Coworking Space,Deli / Bodega,Event Space,Grocery Store,History Museum,Jewish Restaurant,Pizza Place,Prayer Room,Preschool,Private School,Religious School,Sandwich Place,Student Center,Synagogue
0,Albany,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.0,0.0,0.5,0.0,0.000000,0.000000,0.00,0.500000
1,Austin,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.333333,0.00,0.000000,0.333333,0.0,0.0,0.0,0.0,0.000000,0.000000,0.00,0.333333
2,Birmingham,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.00,1.000000
3,Buffalo,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.00,0.000000,0.500000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.00,0.500000
4,Chapel Hill,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.0,0.4,0.0,0.0,0.000000,0.000000,0.00,0.600000
5,Charlotte,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.0,0.0,0.0,0.0,0.500000,0.000000,0.00,0.500000
6,Cincinnati,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.00,1.000000
7,Columbus,0.0,0.0,0.000000,0.0,0.000000,1.000000,0.000000,0.00,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.00,0.000000
8,Dayton,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.0,0.0,0.0,0.0,0.500000,0.000000,0.00,0.500000
9,El Paso,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.0,0.5,0.0,0.0,0.500000,0.000000,0.00,0.000000
10,Hartford,0.0,0.0,0.000000,0.0,0.333333,0.000000,0.000000,0.00,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.00,0.666667
11,Houston,0.0,0.0,0.000000,0.0,0.000000,0.500000,0.000000,0.50,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.00,0.000000
12,Indianapolis,0.0,0.0,0.333333,0.0,0.000000,0.333333,0.000000,0.00,0.000000,0.000000,0.0,0.0,0.0,0.0,0.333333,0.000000,0.00,0.000000
13,Louisville,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.0,0.5,0.0,0.0,0.000000,0.500000,0.00,0.000000
14,Madison,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.00,0.000000,0.250000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.25,0.500000
15,Milwaukee,0.0,0.0,0.000000,0.0,0.000000,1.000000,0.000000,0.00,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.00,0.000000
16,Minneapolis,0.2,0.0,0.000000,0.0,0.000000,0.000000,0.200000,0.00,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.00,0.600000
17,New Haven,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.25,0.000000,0.000000,0.5,0.0,0.0,0.0,0.000000,0.000000,0.25,0.000000
18,New Orleans,0.0,0.2,0.000000,0.2,0.000000,0.200000,0.000000,0.00,0.000000,0.000000,0.0,0.0,0.0,0.0,0.200000,0.000000,0.00,0.200000
19,Orlando,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.0,0.0,0.0,1.0,0.000000,0.000000,0.00,0.000000
20,Pittsburgh,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.0,0.0,0.0,0.0,1.000000,0.000000,0.00,0.000000
21,Portland,0.0,0.0,0.000000,0.0,0.000000,0.166667,0.000000,0.00,0.166667,0.000000,0.0,0.0,0.0,0.0,0.000000,0.166667,0.00,0.500000
22,Richmond,0.0,0.0,0.000000,0.0,0.000000,0.333333,0.000000,0.00,0.333333,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.00,0.333333
23,San Antonio,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.00,1.000000
24,Tucson,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.00,1.000000
25,Youngstown,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.00,1.000000

In [60]:
community_grouped.shape

(26, 19)

In [71]:
num_top_venues = 5

for hood in community_grouped['City']:
    print("----"+hood+"----")
    temp = community_grouped[community_grouped['City'] == hood].T.reset_index()
    temp.columns = ['venue','freq']
    temp = temp.iloc[1:]
    temp['freq'] = temp['freq'].astype(float)
    temp = temp.round({'freq': 2})
    print(temp.sort_values('freq', ascending=False).reset_index(drop=True).head(num_top_venues))
    print('\n')

----Albany----
                 venue  freq
0            Synagogue   0.5
1            Preschool   0.5
2  American Restaurant   0.0
3       Student Center   0.0
4       Sandwich Place   0.0


----Austin----
               venue  freq
0  Jewish Restaurant  0.33
1        Event Space  0.33
2          Synagogue  0.33
3     Breakfast Spot  0.00
4    Coworking Space  0.00


----Birmingham----
                 venue  freq
0            Synagogue   1.0
1  American Restaurant   0.0
2       Student Center   0.0
3       Sandwich Place   0.0
4     Religious School   0.0


----Buffalo----
               venue  freq
0  Jewish Restaurant   0.5
1          Synagogue   0.5
2                Bar   0.0
3     Breakfast Spot   0.0
4    Coworking Space   0.0


----Chapel Hill----
                 venue  freq
0            Synagogue   0.6
1          Prayer Room   0.4
2  American Restaurant   0.0
3       Student Center   0.0
4       Sandwich Place   0.0


----Charlotte----
                 venue  freq
0            Synagogue   0.5
1     Religious School   0.5
2  American Restaurant   0.0
3       Student Center   0.0
4       Sandwich Place   0.0


----Cincinnati----
                 venue  freq
0            Synagogue   1.0
1  American Restaurant   0.0
2       Student Center   0.0
3       Sandwich Place   0.0
4     Religious School   0.0


----Columbus----
            venue  freq
0   Deli / Bodega   1.0
1   Acupuncturist   0.0
2     Pizza Place   0.0
3  Student Center   0.0
4  Sandwich Place   0.0


----Dayton----
                 venue  freq
0            Synagogue   0.5
1     Religious School   0.5
2  American Restaurant   0.0
3       Student Center   0.0
4       Sandwich Place   0.0


----El Paso----
                 venue  freq
0     Religious School   0.5
1          Prayer Room   0.5
2        Acupuncturist   0.0
3  American Restaurant   0.0
4       Student Center   0.0


----Hartford----
             venue  freq
0        Synagogue  0.67
1  Coworking Space  0.33
2      Pizza Place  0.00
3   Student Center  0.00
4   Sandwich Place  0.00


----Houston----
            venue  freq
0   Deli / Bodega   0.5
1   Grocery Store   0.5
2   Acupuncturist   0.0
3     Pizza Place   0.0
4  Student Center   0.0


----Indianapolis----
              venue  freq
0               Bar  0.33
1     Deli / Bodega  0.33
2  Religious School  0.33
3     Acupuncturist  0.00
4       Pizza Place  0.00


----Louisville----
                 venue  freq
0       Sandwich Place   0.5
1          Prayer Room   0.5
2        Acupuncturist   0.0
3  American Restaurant   0.0
4       Student Center   0.0


----Madison----
               venue  freq
0          Synagogue  0.50
1     Student Center  0.25
2  Jewish Restaurant  0.25
3     Breakfast Spot  0.00
4    Coworking Space  0.00


----Milwaukee----
            venue  freq
0   Deli / Bodega   1.0
1   Acupuncturist   0.0
2     Pizza Place   0.0
3  Student Center   0.0
4  Sandwich Place   0.0


----Minneapolis----
             venue  freq
0        Synagogue   0.6
1      Event Space   0.2
2    Acupuncturist   0.2
3   Breakfast Spot   0.0
4  Coworking Space   0.0


----New Haven----
            venue  freq
0     Pizza Place  0.50
1  Student Center  0.25
2   Grocery Store  0.25
3   Acupuncturist  0.00
4  Sandwich Place  0.00


----New Orleans----
                 venue  freq
0            Synagogue   0.2
1       Breakfast Spot   0.2
2        Deli / Bodega   0.2
3     Religious School   0.2
4  American Restaurant   0.2


----Orlando----
                 venue  freq
0       Private School   1.0
1        Acupuncturist   0.0
2  American Restaurant   0.0
3       Student Center   0.0
4       Sandwich Place   0.0


----Pittsburgh----
                 venue  freq
0     Religious School   1.0
1        Acupuncturist   0.0
2  American Restaurant   0.0
3       Student Center   0.0
4       Sandwich Place   0.0


----Portland----
            venue  freq
0       Synagogue  0.50
1  Sandwich Place  0.17
2   Deli / Bodega  0.17
3  History Museum  0.17
4     Pizza Place  0.00


----Richmond----
            venue  freq
0       Synagogue  0.33
1   Deli / Bodega  0.33
2  History Museum  0.33
3     Pizza Place  0.00
4  Student Center  0.00


----San Antonio----
                 venue  freq
0            Synagogue   1.0
1  American Restaurant   0.0
2       Student Center   0.0
3       Sandwich Place   0.0
4     Religious School   0.0


----Tucson----
                 venue  freq
0            Synagogue   1.0
1  American Restaurant   0.0
2       Student Center   0.0
3       Sandwich Place   0.0
4     Religious School   0.0


----Youngstown----
                 venue  freq
0            Synagogue   1.0
1  American Restaurant   0.0
2       Student Center   0.0
3       Sandwich Place   0.0
4     Religious School   0.0

### Let's put that into a pandas dataframe  
##### First, let's write a function to sort the venues in descending order.

In [72]:
def return_most_common_venues(row, num_top_venues):
    row_categories = row.iloc[1:]
    row_categories_sorted = row_categories.sort_values(ascending=False)
    
    return row_categories_sorted.index.values[0:num_top_venues]

In [73]:
num_top_venues = 5

indicators = ['st', 'nd', 'rd']

# create columns according to number of top venues
columns = ['City']
for ind in np.arange(num_top_venues):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

# create a new dataframe
community_neighborhoods_venues_sorted = pd.DataFrame(columns=columns)
community_neighborhoods_venues_sorted['City'] = community_grouped['City']

for ind in np.arange(community_grouped.shape[0]):
    community_neighborhoods_venues_sorted.iloc[ind, 1:] = return_most_common_venues(community_grouped.iloc[ind, :], num_top_venues)

community_neighborhoods_venues_sorted

,City,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue
0,Albany,Synagogue,Preschool,Grocery Store,American Restaurant,Bar
1,Austin,Synagogue,Event Space,Jewish Restaurant,Grocery Store,American Restaurant
2,Birmingham,Synagogue,Student Center,American Restaurant,Bar,Breakfast Spot
3,Buffalo,Synagogue,Jewish Restaurant,Grocery Store,American Restaurant,Bar
4,Chapel Hill,Synagogue,Prayer Room,Grocery Store,American Restaurant,Bar
5,Charlotte,Synagogue,Religious School,Grocery Store,American Restaurant,Bar
6,Cincinnati,Synagogue,Student Center,American Restaurant,Bar,Breakfast Spot
7,Columbus,Deli / Bodega,Synagogue,Student Center,American Restaurant,Bar
8,Dayton,Synagogue,Religious School,Grocery Store,American Restaurant,Bar
9,El Paso,Religious School,Prayer Room,Synagogue,Grocery Store,American Restaurant
10,Hartford,Synagogue,Coworking Space,Student Center,American Restaurant,Bar
11,Houston,Deli / Bodega,Grocery Store,Synagogue,Student Center,American Restaurant
12,Indianapolis,Religious School,Bar,Deli / Bodega,Synagogue,Grocery Store
13,Louisville,Sandwich Place,Prayer Room,Synagogue,Grocery Store,American Restaurant
14,Madison,Synagogue,Jewish Restaurant,Student Center,Grocery Store,American Restaurant
15,Milwaukee,Deli / Bodega,Synagogue,Student Center,American Restaurant,Bar
16,Minneapolis,Synagogue,Event Space,Acupuncturist,Religious School,Private School
17,New Haven,Pizza Place,Grocery Store,Student Center,Synagogue,American Restaurant
18,New Orleans,Synagogue,American Restaurant,Religious School,Breakfast Spot,Deli / Bodega
19,Orlando,Private School,Synagogue,Grocery Store,American Restaurant,Bar
20,Pittsburgh,Religious School,Synagogue,Grocery Store,American Restaurant,Bar
21,Portland,Synagogue,Deli / Bodega,History Museum,Sandwich Place,Religious School
22,Richmond,Synagogue,Deli / Bodega,History Museum,Religious School,Private School
23,San Antonio,Synagogue,Student Center,American Restaurant,Bar,Breakfast Spot
24,Tucson,Synagogue,Student Center,American Restaurant,Bar,Breakfast Spot
25,Youngstown,Synagogue,Student Center,American Restaurant,Bar,Breakfast Spot

# Cluster Neighborhoods

### Run k-means to cluster the neighborhood into 5 clusters

In [74]:
# set number of clusters
kclusters = 4

community_grouped_clustering = community_grouped.drop('City', 1)

# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(community_grouped_clustering)

# check cluster labels generated for each row in the dataframe
kmeans.labels_[0:10]

array([2, 2, 1, 2, 2, 3, 1, 0, 3, 3])

In [75]:
# add clustering labels
community_neighborhoods_venues_sorted.insert(0, 'Cluster Labels', kmeans.labels_)

community_merged = num_of_jew_df

# merge toronto_grouped with toronto_data to add latitude/longitude for each neighborhood
community_merged = community_merged.join(community_neighborhoods_venues_sorted.set_index('City'), on='City')

community_merged

,City,Number,Latitude,Longtitude,State,Short_state,1990,2017,change,Cluster Labels,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue
0,Houston,48400,29.7589,-95.3677,Texas,TX,109000,166505,57505,0.0,Deli / Bodega,Grocery Store,Synagogue,Student Center,American Restaurant
1,Austin,16300,30.2711,-97.7437,Texas,TX,109000,166505,57505,2.0,Synagogue,Event Space,Jewish Restaurant,Grocery Store,American Restaurant
2,San Antonio,12740,29.4246,-98.4951,Texas,TX,109000,166505,57505,1.0,Synagogue,Student Center,American Restaurant,Bar,Breakfast Spot
3,El Paso,5000,31.76,-106.487,Texas,TX,109000,166505,57505,3.0,Religious School,Prayer Room,Synagogue,Grocery Store,American Restaurant
4,Portland,47500,45.5202,-122.674,Oregon,OR,12500,40650,28150,2.0,Synagogue,Deli / Bodega,History Museum,Sandwich Place,Religious School
5,Pittsburgh,42200,40.4417,-79.9901,Pennsylvania,PA,330500,291140,-39360,3.0,Religious School,Synagogue,Grocery Store,American Restaurant,Bar
6,Minneapolis,40240,44.9773,-93.2655,Minnesota,MN,30500,45600,15100,2.0,Synagogue,Event Space,Acupuncturist,Religious School,Private School
7,Hartford,34500,41.7646,-72.6909,Connecticut,CT,113200,117850,4650,1.0,Synagogue,Coworking Space,Student Center,American Restaurant,Bar
8,New Haven,29700,41.3082,-72.9251,Connecticut,CT,113200,117850,4650,2.0,Pizza Place,Grocery Store,Student Center,Synagogue,American Restaurant
9,Cincinnati,27000,39.1015,-84.5125,Ohio,OH,130800,147715,16915,1.0,Synagogue,Student Center,American Restaurant,Bar,Breakfast Spot
10,Columbus,25500,39.9623,-83.0007,Ohio,OH,130800,147715,16915,0.0,Deli / Bodega,Synagogue,Student Center,American Restaurant,Bar
11,Dayton,4000,39.7589,-84.1916,Ohio,OH,130800,147715,16915,3.0,Synagogue,Religious School,Grocery Store,American Restaurant,Bar
12,Toledo,3900,41.6787,-83.5127,Ohio,OH,130800,147715,16915,NaN,NaN,NaN,NaN,NaN,NaN
13,Youngstown,3200,41.1036,-80.652,Ohio,OH,130800,147715,16915,1.0,Synagogue,Student Center,American Restaurant,Bar,Breakfast Spot
14,Milwaukee,25800,43.035,-87.9225,Wisconsin,WI,34700,33055,-1645,0.0,Deli / Bodega,Synagogue,Student Center,American Restaurant,Bar
15,Madison,5000,43.0748,-89.3838,Wisconsin,WI,34700,33055,-1645,2.0,Synagogue,Jewish Restaurant,Student Center,Grocery Store,American Restaurant
16,Tucson,22900,32.2219,-110.926,Arizona,AZ,71500,106725,35225,1.0,Synagogue,Student Center,American Restaurant,Bar,Breakfast Spot
17,Rochester,22500,43.1573,-77.6152,New York,NY,1843000,1759570,-83430,NaN,NaN,NaN,NaN,NaN,NaN
18,Buffalo,13000,42.8867,-78.8784,New York,NY,1843000,1759570,-83430,2.0,Synagogue,Jewish Restaurant,Grocery Store,American Restaurant,Bar
19,Albany,12500,42.6512,-73.755,New York,NY,1843000,1759570,-83430,2.0,Synagogue,Preschool,Grocery Store,American Restaurant,Bar
20,Kansas City,19000,39.1135,-94.6265,Kansas,KS,14000,17300,3300,NaN,NaN,NaN,NaN,NaN,NaN
21,Orlando,19000,28.5421,-81.379,Florida,FL,567000,621460,54460,2.0,Private School,Synagogue,Grocery Store,American Restaurant,Bar
22,Jacksonville,15000,30.3322,-81.6557,Florida,FL,567000,621460,54460,NaN,NaN,NaN,NaN,NaN,NaN
23,Providence,14200,41.8677,-71.5815,Rhode Island,RI,16100,18750,2650,NaN,NaN,NaN,NaN,NaN,NaN
24,Richmond,12500,37.5385,-77.4343,Virginia,VA,67600,95695,28095,2.0,Synagogue,Deli / Bodega,History Museum,Religious School,Private School
25,Charlotte,12000,35.2271,-80.8431,North Carolina,NC,16300,35435,19135,3.0,Synagogue,Religious School,Grocery Store,American Restaurant,Bar
26,Chapel Hill,6000,35.9132,-79.0558,North Carolina,NC,16300,35435,19135,2.0,Synagogue,Prayer Room,Grocery Store,American Restaurant,Bar
27,Raleigh,6000,35.7804,-78.6391,North Carolina,NC,16300,35435,19135,NaN,NaN,NaN,NaN,NaN,NaN
28,Greensboro,3000,36.0726,-79.792,North Carolina,NC,16300,35435,19135,NaN,NaN,NaN,NaN,NaN,NaN
29,New Orleans,12000,29.9499,-90.0701,Louisiana,LA,15700,13900,-1800,2.0,Synagogue,American Restaurant,Religious School,Breakfast Spot,Deli / Bodega
30,Indianapolis,10000,39.7683,-86.1584,Indiana,IN,18300,17345,-955,3.0,Religious School,Bar,Deli / Bodega,Synagogue,Grocery Store
31,Louisville,8700,38.2542,-85.7594,Kentucky,KY,11800,11200,-600,2.0,Sandwich Place,Prayer Room,Synagogue,Grocery Store,American Restaurant
32,Nashville,8000,36.1622,-86.7744,Tennessee,TN,19400,19800,400,NaN,NaN,NaN,NaN,NaN,NaN
33,Birmingham,5300,33.5207,-86.8024,Alabama,AL,9300,9525,225,1.0,Synagogue,Student Center,American Restaurant,Bar,Breakfast Spot
34,Montgomery,1200,32.367,-86.3006,Alabama,AL,9300,9525,225,NaN,NaN,NaN,NaN,NaN,NaN

In [78]:
# create map
map_clusters = folium.Map(location=[latitude, longitude], zoom_start=4)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i + x + (i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
community_merged['Cluster Labels'].dropna(inplace=True)
for lat, lon, poi, cluster in zip(community_merged['Latitude'], community_merged['Longtitude'], community_merged['City'], community_merged['Cluster Labels']):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[int(cluster)-1],
        fill=True,
        fill_color=rainbow[int(cluster)-1],
        fill_opacity=0.7).add_to(map_clusters)
       
map_clusters